version: '2'
services:
    server:
        image: node:8.1
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - ./services/frontend/server:/usr/src/app
        environment:
            NODE_ENV: development
            LOG_LEVEL: ${LOG_LEVEL}
            SERVER_PORT: ${SERVER_PORT}
            SERVER_NAME: ${SERVER_NAME}
            SERVER_SECRET: ${SERVER_SECRET}
        working_dir: /usr/src/app
        entrypoint: ["yarn", "run:dev"]
